/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lSotRhA5lUa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Chivo } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    <div className="relative w-full min-h-[100dvh] flex flex-col justify-center items-center bg-gray-900 overflow-hidden">
      <span className="absolute inset-0 w-full h-full object-cover opacity-50 rounded-md bg-gray-100 dark:bg-gray-800" />
      <div className="relative z-10 max-w-3xl px-6 py-12 sm:px-12 sm:py-20 text-center">
        <h1 className="text-4xl font-bold text-white mb-4 sm:text-5xl sm:mb-6">Welcome to our Platform</h1>
        <p className="text-lg text-gray-300 mb-8 sm:text-xl sm:mb-12">
          Discover the power of our cutting-edge tools and services.
        </p>
        <div className="flex justify-center space-x-4">
          <Link
            className="inline-flex items-center justify-center px-6 py-3 bg-blue-500 text-white font-medium rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            href="#"
          >
            Sign Up
          </Link>
          <Link
            className="inline-flex items-center justify-center px-6 py-3 bg-transparent text-white font-medium rounded-md hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2"
            href="#"
          >
            Sign In
          </Link>
        </div>
      </div>
    </div>
  )
}
